name: Deploy to VPS

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: SSH connect to VPS
        uses: appleboy/ssh-action@master
        with:
          host: 85.192.42.30
          username: root
          key: ${{ secrets.VPS }}
          script: |
            cd /apps
            git pull
            docker-compose up -d --build
